config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   resources :gossips
   resources :author
   resources :cities
   resources :users

   root 'gossips#index'
   get '/static_pages/team', to: 'static_pages#team', as: 'team'
   get '/static_pages/contact', to: 'static_pages#contact', as: 'contact'
   get '/welcome/:index', to: 'welcome#index'
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	#La relation est qu'un gossip est écrit pas un seul user
	belongs_to :user
	#mais qu'un gossip peut avoir plusieur tag
	has_many :tag_gossips
	has_many :tags, through: :tag_gossip

#Validation titre
	validates :title, presence: { message: "Le titre doit être renseigné"}

  validates :title, length: {minimum: 3, maximum: 14, message: "le titre doit etre compris entre 3 et 14 caracteres"}

	validates :title, uniqueness: { message: "Ce titre est déjà pris."}



#Validation contenu

validates :content, presence: { message: "le contenu doit être renseigné."}
validates :content, length: {minimum: 20, message: "Le contenu doit faire au moins 20 caracteres"}


end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @gossip = Gossip.all
    @user = User.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = User.all

  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @gossip = Gossip.new
  end


  def create
    # Méthode qui créé un potin à partir du contenu du formulaircite de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
  #anonymous=User.new(first_name:"Anonymous", last_name:"unknown",age: 99,description: "unknown",email:"unknown#{rand(1000)}@mail.com",city_id:City.all.sample.id)
  #anonymous.save
  @gossip = Gossip.create(title: params[:title], content: params[:content], user_id: 2) # avec xxx qui sont les données obtenues à partir du formulaire

  if @gossip.save # essaie de sauvegarder en base @gossip
    # si ça marche, il redirige vers la page d'index du site
       @gossips=Gossip.all
      redirect_to gossips_path
  else
    # sinon, il render la view new (qui est celle sur laquelle on est déjà)
  render 'new'
  end

  end


  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  @gossip = Gossip.find(params[:id])
  end

  def update
    
     @gossip = Gossip.find(params[:id])
     post_params = params.permit(:title, :content)

     if @gossip.update(post_params, user_id: 2) #title: params[:title], content: params[:content]
     @gossips=Gossip.all
     redirect_to gossips_path

     else
     render :edit
  
end
end


  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    

    @gossip = Gossip.find(params[:id])

   if  @gossip.destroy
       redirect_to gossips_path 
    else render :show
  end
end
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
 <%= form_tag url_for(action: 'update'), method: "patch" do %>
   <!-- <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> -->
   <h1> Ici, tu peux updater ton potin!</h1>

      <%= label_tag 'Nouveau titre du gossip' %>
      <%= text_field_tag 'title'%>
      <br /> <br />

      <%= label_tag 'Nouveau contenu du gossip' %>
      <%= text_area_tag 'content' %>
      <br /> <br />

      

      <%= submit_tag 'Create Post' %>

    <% end %>

app/views/gossips/index.html.erb
<h1 class= "text-center display-4">BIENVENUE</h1>

<h4> Tu veux créer un Gossip ? C'est <a href="<%= new_gossip_path%>">là</a> !</h4>
<br>
<div class="">
<% @gossip.each do |t| %>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= @user.find(t.user_id).first_name%></h5>
        <p class="card-text"><%= t.content %></p>
        <a class="btn btn-outline-danger" href="<%= gossip_path(t) %>">Afficher le potin</a>
        <a href="<%= gossip_path(t) %>" class="btn btn-danger" data-confirm="Êtes vous sûr de vouloir supprimer ce gossip?" data-method="DELETE">Supprimer</a>
        
      </div>
    </div>
  </div>
</div>




<br><br>
<% end %>

app/views/gossips/new.html.erb
<html>
  <body>
    <!-- ... -->

    <%= form_tag url_for(action: 'create'), method: "post" do %>
   <!-- <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> -->
      <%= label_tag 'Titre du gossip' %>
      <%= text_field_tag 'title'%>
      <br /> <br />

      <%= label_tag 'Contenu du gossip' %>
      <%= text_area_tag 'content' %>
      <br /> <br />

      

      <%= submit_tag 'Create Post' %>

    <% end %>

    <!-- ... -->
  </body>
</html>

app/views/gossips/show.html.erb
  <% tab_date = ["13/01/2019", "25/11/2007", "12/09/2018", "23/05/2006"] %>

Bienvenue sur la page du potin!

    <div class="card text-center" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= @gossip.title %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= tab_date.sample %></h6>
        <p class="card-text"><%= @gossip.content %></p>
        <p class="card-link"><%= link_to "Ville", city_path(@gossip.user.id) %> </p>
        <p class="card-link"><%= link_to @user.find(@gossip.user_id).first_name ,author_path(@gossip.user_id)%> </p>
        <p class="card-link"><%= link_to "Editer le potin", edit_gossip_path %>

        <%= form_tag url_for(action: 'destroy'), method: "DELETE" do %>
		<%= submit_tag 'Supprimer' %>
		<% end %> 
		
      </div>
    </div>